In [29]:
import numpy as np
import sys,os
sys.path.append(os.pardir)
from common.functions import softmax,cross_entropy_error
from common.gradient import numerical_gradient

# 4.4 勾配

In [2]:
def numerical_gradient(f,x):
    h = 1e-4
    grad = np.zeros_like(x)
    
    for idx in range(x.size):
        tmp_val = x[idx]
        # f(x+h)の計算
        x[idx] = tmp_val + h
        fxh1 = f(x)
        
        # f(x-h)の計算
        x[idx] = tmp_val -h 
        fxh2 = f(x)
        
        grad[idx] = (fxh1-fxh2)/(2*h)
        x[idx] = tmp_val# 元に
        
    return grad

In [4]:
def function_2(x):
    return x[0]**2 + x[1]**2

In [16]:
numerical_gradient(function_2, np.array([3.0,4.0]))

array([6., 8.])

In [20]:
# 勾配降下法

def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x
    
    for i in range(step_num):
        grad = numerical_gradient(f,x)
        x -= lr*grad
        
    return x

In [21]:
init_x = np.array([-3.0, 4.0])

In [26]:
gradient_descent(function_2,init_x=init_x, lr=1e-10
                 , step_num=100)

array([-6.11098557e-10,  8.14798076e-10])

In [30]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3) #ガウス分布で初期化
        
    def predict(self,x):
        return np.dot(x,self.W)
    
    def loss(self,x,t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y,t)
        
        return loss

In [31]:
net=simpleNet()
print(net.W)

[[-0.32590711  0.83198222 -0.1073399 ]
 [-0.33862716  0.34796496  1.18372333]]


In [34]:
x=np.array([0.6,0.9])
p=net.predict(x)
print(p)

[-0.50030871  0.8123578   1.00094706]


In [35]:
np.argmax(p)

2

In [36]:
t = np.array([0,0,1])
net.loss(x,t)

0.7183159252057539

In [37]:
def f(W):
    return net.loss(x,t)

In [38]:
dW = numerical_gradient(f,net.W)
print(dW)

[[ 0.06519336  0.24226304 -0.30745639]
 [ 0.09779003  0.36339456 -0.46118459]]
